package ltd.newbee.mall.controller.mall;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.time.Duration;
import java.util.*;

public class OrderTest_Automated {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  Actions actions;
  WebDriverWait wait;
  @Before
  public void setUp() {
    System.setProperty("webdriver.gecko.driver", "D:\\selenium\\geckodriver.exe");
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    vars = new HashMap<String, Object>();
    wait = new WebDriverWait(driver, Duration.ofSeconds(5)); // 设置显式等待时间为5秒
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void orderTest_Automated() throws Exception {
    driver.get("http://localhost:28079/login");
    driver.manage().window().setSize(new Dimension(2062, 1118));
    driver.findElement(By.id("loginName")).click();
    driver.findElement(By.id("loginName")).sendKeys("13616745302");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("tsh123456");
    String captchaCode = getCaptchaCode("mallVerifyCode");
    driver.findElement(By.id("verifyCode")).click();
    driver.findElement(By.id("verifyCode")).sendKeys(captchaCode);
    driver.findElement(By.cssSelector(".submit")).click();
    driver.findElement(By.cssSelector(".hot-image:nth-child(1) img")).click();
    driver.findElement(By.cssSelector(".car:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".swal-button--confirm")).click();
    driver.findElement(By.cssSelector(".shopcart")).click();
    driver.findElement(By.name("settle")).click();
    driver.findElement(By.linkText("修改")).click();
    driver.findElement(By.id("address")).click();
    driver.findElement(By.id("address")).sendKeys("123456787878123456");
    driver.findElement(By.id("saveButton")).click();
    driver.findElement(By.id("saveOrder")).click();
    driver.findElement(By.linkText("去支付")).click();
    driver.findElement(By.cssSelector("#J_weixin > img")).click();
    driver.findElement(By.linkText("支付成功")).click();
    driver.findElement(By.linkText("取消订单")).click();
    driver.findElement(By.cssSelector(".swal-button--confirm")).click();
  }

  private String getCaptchaCode(String attributeName) {
    try {
      String script = "var xhr = new XMLHttpRequest();" +
              "xhr.open('GET', 'http://localhost:28079/getSessionAttribute?attributeName=' + arguments[0], false);" +
              "xhr.send(null);" +
              "return xhr.responseText;";
      return (String) js.executeScript(script, attributeName);
    } catch (Exception e) {
      e.printStackTrace();
      return "error";
    }
  }
}
